name: Notebook Check

on:
  push:
  pull_request:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute notebook
        run: jupyter nbconvert --to notebook --execute "Netflix Analysis.ipynb" --output executed-notebook.ipynb
